name: flutter_photokit
description: Flutter plugin for interacting with PhotoKit on iOS. Contains methods for saving photos/videos to user's camera roll or custom albums.
author: Crater Dev Team <dev@crater.land>
homepage: https://github.com/kmorkos/flutter_photokit
version: 0.1.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  path_provider: 0.4.1

flutter:
  plugin:
    androidPackage: land.crater.flutterphotokit
    pluginClass: FlutterPhotokitPlugin
